### ISSUE TITLE
Error occurred on loras

### ISSUE THREAD

**Issue by Crd1140234468** [showlab/MotionDirector#11]
Hi, thanks for releasing the nice work.
When I try to run the Train MotionDirector on a single video, using the provided data ''./test_data/car_turn/car-turn-24.mp4'', the code encounters an error
Traceback (most recent call last):
   File "MotionDirector_train.py", line 1024, in <module>
     main(**OmegaConf.load(args.config))
   File "MotionDirector_train.py", line 894, in main
     loss_spatial, loss_temporal, latents, init_noise = finetune_unet(batch, step, mask_spatial_lora=mask_spatial_lora, mask_temporal_lora=mask_temporal_lora)
   File "MotionDirector_train.py", line 820, in finetune_unet
     loras[lora_idx + step].scale = 1.
IndexError: list index out of range

What is going on?

**Comment by ruizhaocv** [comment]
Hi. Which config file did you use? Did you set the num_frames to 24?

**Comment by Crd1140234468** [comment]
> Hi. Which config file did you use? Did you set the num_frames to 24?

I am using config_single_video_24.yaml, and when only replacing the training video, I found that using my own video will detect num_examples=2, what is the reason?

**Comment by Crd1140234468** [comment]
But after I restored all the default settings of ''config_single_video_24.yaml'', the demo''car_turn/car-turn-24.mp4'' can be trained.

**Comment by Crd1140234468** [comment]
Thank you for your reply. I have successfully trained my own video according to the newly updated scripts. In addition, if the training video used exceeds 24 frames, will it affect the training effect?

**Comment by ruizhaocv** [comment]
It's OK. I think it will not will not significantly impact the results.
