### ISSUE TITLE
problem about training for image animation

### ISSUE THREAD

**Issue by jetterson** [showlab/MotionDirector#16]
Thanks for releasing the nice work. 
when I run the command,"python MotionDirector_train.py --config ./configs/config_single_image.yaml"
the following error occurs:
Traceback (most recent call last):
   File "MotionDirector_train.py", line 1050, in <module>
     main(**OmegaConf.load(args.config))
   File "MotionDirector_train.py", line 912, in main
     loss_spatial, loss_temporal, latents, init_noise = finetune_unet(batch, step, mask_spatial_lora=mask_spatial_lora, mask_temporal_lora=mask_temporal_lora)
   File "MotionDirector_train.py", line 836, in finetune_unet
     loras = extract_lora_child_module(unet, target_replace_module=["TransformerTemporalModel"])
   File "/home/MotionDirector/utils/lora.py", line 702, in extract_lora_child_module
     raise ValueError("No lora injected.")
ValueError: No lora injected.
Why does this happen? And how can I solve it?

**Comment by ruizhaocv** [comment]
Hi jetterson. This is because I forgot to update the lora.py. I just updated it.
